### ISSUE TITLE
Error messages on checkout from Drupal Commerce

### ISSUE THREAD

**Issue by superbole** [PayFast/mod-drupalcommerce-7#1]
When processing a payment from Drupal Commerce I get the following errors:

Off-site payment redirect
Error message

Notice: Undefined index: und in commerce_payfast_redirect_form() (line 89 ofC:\Domains\mysitename.co.za\SubDomains\drupal\sites\all\modules\commerce_payfast\commerce_payfast.module).
Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->load() (line 175 ofC:\Domains\mysitename.co.za\SubDomains\drupal\includes\entity.inc).
Notice: Trying to get property of non-object in commerce_payfast_redirect_form() (line 90 ofC:\Domains\mysitename.co.za\SubDomains\drupal\sites\all\modules\commerce_payfast\commerce_payfast.module).
Warning: array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController->load() (line 175 ofC:\Domains\mysitename.co.za\SubDomains\drupal\includes\entity.inc).
Notice: Trying to get property of non-object in commerce_payfast_redirect_form() (line 91 ofC:\Domains\mysitename.co.za\SubDomains\drupal\sites\all\modules\commerce_payfast\commerce_payfast.module).
Notice: Trying to get property of non-object in commerce_payfast_redirect_form() (line 101 ofC:\Domains\mysitename.co.za\SubDomains\drupal\sites\all\modules\commerce_payfast\commerce_payfast.module).

Do you have any suggestions for me to proceed? This is very urgent as I have an online event registration which was supposed to go live today.

This is happening on my development and production sites and on live and sandbox.

**Comment by Brendon-P** [comment]
Hi,
Please can you submit a support ticket to support@payfast.co.za with the subject 'Drupal' as this will allow us to respond to your query faster.
Thank you
